### ISSUE TITLE
Can this be used with mux-player?

### ISSUE THREAD

**Issue by bubbleheadinc** [muxinc/media-group#64]
Hi, I've stumbled across your repo. It looks like it would be a big help in my project where I"m trying to sync two videos. 

I have tried to use it with `<mux-player>`, but can't seem to get it going. It works fine with html video elements (in Safari anyway b/c of native HLS). I have put together a test Code Sandbox demonstrating it. The video elements (commented out in the sandbox) will sync, but you can see the mux players don't. Have you been able to get them to sync? Am I missing something?

https://codesandbox.io/s/media-group-mux-player-f9oxdp?file=/index.html

Thanks so much!

**Comment by bubbleheadinc** [comment]
Correct me if I'm wrong, but I think it may be because the media-group script needs to be able to find the video element on the page? In the Mux player, it's buried in shadow DOMs, so it can't find the video tags?

**Comment by luwes** [comment]
thanks for reporting this, I'll have a look at this soon.

> Correct me if I'm wrong, but I think it may be because the media-group script needs to be able to find the video element on the page? In the Mux player, it's buried in shadow DOMs, so it can't find the video tags?

I believe it can work with the video API Mux player exposes so it shouldn't be that.

**Comment by luwes** [comment]
thanks again for the feedback! should be fixed https://media-group-mux.vercel.app/examples/mux-player.html
