### ISSUE TITLE
Using as import

### ISSUE THREAD

**Issue by bubbleheadinc** [muxinc/media-group#66]
Hi again..I'm trying to use your lib in Vue3 and as an import statement instead of from a CDN in a script tag. It's quite possible I'm just doing something incorrectly. Have you successfully used it in a JS framework as an import?

Example: https://codesandbox.io/s/practical-chaplygin-tmncwi?file=/src/components/HelloWorld.vue

Thanks!

**Comment by luwes** [comment]
thanks for the Codesandbox!

not exactly sure what is going on, if you manually re-set the group attribute on mount it starts to work
https://codesandbox.io/s/angry-hill-sywc3x?file=/src/components/HelloWorld.vue

plain JS imports work fine 
https://codesandbox.io/s/media-group-imported-hj8dmk?file=/src/index.js


I'm guessing it's something with the mutation observer not picking up the changes of Vue added elements.

**Comment by bubbleheadinc** [comment]
Excellent, thanks! Yeah, not sure either, but you got me going in a workable direction...I changed the Codesandbox to use binding of the group and that seems to work without having to set the attribute (more Vue friendly maybe). https://codesandbox.io/s/intelligent-jones-515j0h?file=/src/components/HelloWorld.vue

Although, it still doesn't work in my app. It seems like the module isn't being imported for some reason, so I have to resort to manually loading the script for now like this, which does work:

```
const loadMediaGroupScript = () => {
  const existingMediaGroupSyncScriptTag = document.getElementById("mediaGroupSyncScript");

  if (!existingMediaGroupSyncScriptTag) {
    let mediaGroupScript = document.createElement("script");

    mediaGroupScript.setAttribute("type", "module");
    mediaGroupScript.setAttribute("src", "https://cdn.jsdelivr.net/npm/media-group");
    mediaGroupScript.setAttribute("id", "mediaGroupSyncScript");

    document.head.appendChild(mediaGroupScript);
  }
};
```
But I have other complexities going on in my app, so must be app specific since it works fine in the Codesandbox. Thanks again for the lib and all the help!
